### ISSUE TITLE
Is this project still worth using?

### ISSUE THREAD

**Issue by darkedges** [mozilla/build-fwunit#46]
Morning All,
just checking to see if this project is still valid today?

Reason for asking is that I am looking for a version for Azure Application and Network Security groups and this is the only type of unit testing tool that I can find.

Are there any alternatives that I should look at?

Regards
Nicholas Irving

**Comment by djmitche** [comment]
I don't think it's used much at Mozilla anymore (I've moved on to other teams, at any rate).  But the project itself is still quite valid.  It has a structural limitation that may make it unsuitable for you, though: it assumes a single, fairly static IP space.  So if your Azure systems are dynamically creating networks, this may not be a great fit.

Even if that's the case, the *approach* embodied by fwunit is the neat thing.  The code is basically just some command-line goodness along with an efficient way to model a full IP-to-IP mapping and utilities for constructing that mapping from various sources.  So it may make sense to implement something following the same model that meets your needs: make some Azure API calls to gather the current state, represent it in a way that is easy to make assertions about, and then write some tests in your favorite testing framework.

HTH!

**Comment by darkedges** [comment]
Thanks will have a look and see what I can do.
